version: '3'
services:
  frontend:
    build: ./my-new/
    ports:
      - "80:80"

  backend:
    build: ./node1/
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres   
      POSTGRES_DB: demo
    volumes:
      - ./moviess.sql:/docker-entrypoint-initdb.d/moviess.sql   

volumes:
  db_data:
